Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder "./ansible", "/home/vagrant/ansible",
    create: true, type: :rsync, owner: :vagrant, group: :vagrant,
    rsync__exclude: [
      ".git/",
      "*.swp",
    ]

  config.vm.provider :virtualbox do |vb|
    vb.gui    = false
    vb.memory = 1024 * 2
    vb.cpus   = 2
  end

  config.vm.define :athena_sample do |machine|
    machine.vm.hostname = "athena-sample"
    machine.vm.network "private_network", ip: "#{ENV['ATHENA_SAMPLE_IP'] || '192.168.33.11'}"
    machine.vm.provider :virtualbox do |vb|
      vb.name = "athena-sample"
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook       = "/home/vagrant/ansible/main.yml"
    ansible.inventory_path = "/home/vagrant/ansible/inventories/hosts"
    ansible.version        = "latest"
    ansible.limit          = "my-hosts"
    ansible.verbose        = false # デバッグしない
    ansible.install        = true  # Ansibleを自動インストールする
  end
end
